// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: chat_gpt

#include "../ui.h"

void EventDalleImageClick(lv_event_t *e);

void ui_ScreenImage_screen_init(void)
{
    ui_ScreenImage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenImage, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_img_src(ui_ScreenImage, &ui_img_setup_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DalleImage = lv_img_create(ui_ScreenImage);
    lv_obj_set_width(ui_DalleImage, 240);
    lv_obj_set_height(ui_DalleImage, 240);
    lv_obj_align(ui_DalleImage, LV_ALIGN_CENTER, 0, 0);
    // lv_obj_set_width(ui_DalleImage, LV_SIZE_CONTENT);
    // lv_obj_set_height(ui_DalleImage, LV_SIZE_CONTENT);
    lv_obj_add_flag(ui_DalleImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_DalleImage, LV_OBJ_FLAG_SCROLLABLE);                        /// Flags

    lv_obj_add_event_cb(ui_DalleImage, EventDalleImageClick, LV_EVENT_CLICKED, NULL);
}
